#
# Module manifest for module 'ExeTools'
#
# Generated by: Sedat Kapanoglu
#
# Generated on: 11/3/2022
#

@{
    RootModule             = "ExeTools.psm1"
    # Version number of this module.
    ModuleVersion          = '0.2.2'

    # ID used to uniquely identify this module
    GUID                   = '9dfbbd88-a2eb-43f9-850d-9af0d6f273fa'

    # Author of this module
    Author                 = 'Sedat Kapanoglu'

    # Copyright statement for this module
    Copyright              = '(c) 2022 Sedat Kapanoglu. All rights reserved.'

    # Description of the functionality provided by this module
    Description            = 'Provides the cmdlet Get-ExeArchitecture'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion      = '7.0'

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    DotNetFrameworkVersion = '5.0'
}